#include "LinkedLists.h"

int main() {
    FILE *f;
    TList *Synonyms = getSynWords(f);
    TList *Antonyms = getAntoWords(f);
    // deleteWord(f,Synonyms,Antonyms,"bright");
    // printWords(Synonyms,0);
    // printWords(Antonyms,45);
    // TList *search = similarWord(Synonyms,"und",90);
    // printf("\n\n");
    // printWords(search, 0);
    // printf("\n\n");
    // TList *substring = countWord(Synonyms,"ast");
    // printWords(substring,0);
    // TList *palldromeList = palindromWord(Synonyms);
    // printWords(palldromeList,0);
    TList2 *Merged = merge(Synonyms,Antonyms);
    // printWords2(Merged);
    // TList3 *Merged2 = merge2(Synonyms,Antonyms);
    // printWords3(Merged2);
    // addWord(f,Synonyms,Antonyms,"abdou","rayes","3amek");
    // printWords(Synonyms,0);
    // TQueue* syllables = syllable(Synonyms);
    // printQueueWords(syllables);
    TStack *stk = toStack(Merged);
    printf("\n\n");
    // printf("Length Stack = %d\n",lengthStack(stk));
    TStack *newStack = syllableStack(stk);
    printStack(newStack);
    // TStack **stacks = prounounciationStack(stk);
    // for(int i = 0 ; i < 3 ; i++) {printf("\n\n\nStack %d :\n",i);printStack(stacks[i]);}
    // printStack(stk);
    // printf("\n\n");
    // getInfWordStack(stk,"radar");
    // printf("\n\n");
    // printStack(stk);
    // stk = sortWordStack(stk);
    // printStack(stk);
    // deleteWordStack(stk,"underpay");
    // printStack(stk);
    // stk = updateWordStack(stk,"unsafe","under-risk","safe");
    // printStack(stk);
    // TQueue *queue = stackToQueue(stk);
    // printQueueWords(queue);
    // printf("\nList :\n");
    // TList2 *list = StacktoList(stk);
    // printWords2(list);
    // printf("\nSorted Inssertion : \n");
    // stk = sortWordStack(stk);
    // stk = addWordStack(stk,"unabdou","unbeliveable","bad");
    // printStack(stk);
    // char *word = getSmallest(stk);
    // printf("string = %s\n",word);
    // printf("%d %d %d \n",isPalyndromeStack("abdou"),isPalyndromeStack("racecar"),isPalyndromeStack("hi"));
    // printf("Reversed Stac");
    // stk = StackRev(stk);
    // printStack(stk);
    // printf("\nsysllabels = %d\n",count_syllables("lion"));
    // TQueue * q = syllable(Synonyms);
    // printQueueWords(q);
    // TQueue **queues = prounounciation(Synonyms);
    // printf("Short : \n");
    // printQueueWords(queues[0]);
    // printf("Long : \n");
    // printQueueWords(queues[1]);
    // printf("Diphthong : \n");
    // printQueueWords(queues[2]);
    // TQueue *q = toQueue(Merged);
    // printQueueWords(q);
    return 0;
}